banner: |
  /*!
   * <%= package.name %> - <%= package.description %>
   * v<%= package.version %>
   * <%= package.homepage %>
   * copyright <%= package.copyright %> <%= grunt.template.today("yyyy") %>
   * <%= package.license %> License
  */